name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build UI
      run: cd & cd ./src/ui & npm ci & npm run build & cd ../..
      
#    - name: Build
#      run: cargo build --release --verbose
#
#    - name: Run tests
#      run: cargo test --verbose
#
#    - name: Copy builds
#      run: mkdir -p ./build/ui/ & cp ./target/release/derby-stats ./build/ & cp -r ./src/ui/dist/* ./build/ui/

  build-windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build UI
      run: cd src\ui & npm ci & npm run build & cd ..\..
      
#    - name: Build
#      run: cargo build --release --verbose
#
#    - name: Run tests
#      run: cargo test --verbose
#
#    - name: Copy builds
#      run: mkdir .\build\ui\ & xcopy .\target\release\derby-stats .\build\ & xcopy .\src\ui\dist\ .\build\ui\ /E
      
