name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build UI
      working-directory: ./src/ui
      run: |
        npm ci
        npm run build
      
    - name: Build
      run: cargo build --release --verbose

    - name: Copy builds
      run: |
        mkdir -p ./build/ui/
        cp ./target/release/derby-stats ./build/
        cp -r ./src/ui/dist/* ./build/ui/

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-linux-x64
        path: ./build/**

  build-windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build UI
      working-directory: .\src\ui
      run: |
        npm ci
        npm run build
      
    - name: Build
      run: cargo build --release --verbose

    - name: Copy builds
      run: |
        mkdir .\build\ui\
        xcopy .\target\release\derby-stats.exe .\build\
        xcopy .\src\ui\dist\ .\build\ui\ /E

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-windows-x64
        path: .\build\**
        
